# Generated by Django 3.2.5 on 2021-07-24 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableoftodo',
            old_name='what_to_do',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_date',
            new_name='due',
        ),
        migrations.AddField(
            model_name='tableoftodo',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
